label define DNAME 1 `"Achham        "', modify
label define DNAME 2 `"Arghakhanchi  "', modify
label define DNAME 3 `"Baglung       "', modify
label define DNAME 4 `"Baitadi       "', modify
label define DNAME 5 `"Bajhang       "', modify
label define DNAME 6 `"Bajura        "', modify
label define DNAME 7 `"Banke         "', modify
label define DNAME 8 `"Bara          "', modify
label define DNAME 9 `"Bardiya       "', modify
label define DNAME 10 `"Bhaktapur     "', modify
label define DNAME 11 `"Bhojpur       "', modify
label define DNAME 12 `"Chitawan      "', modify
label define DNAME 13 `"Dadeldhura    "', modify
label define DNAME 14 `"Dailekh       "', modify
label define DNAME 15 `"Dang          "', modify
label define DNAME 16 `"Darchula      "', modify
label define DNAME 17 `"Dhading       "', modify
label define DNAME 18 `"Dhankuta      "', modify
label define DNAME 19 `"Dhanusa       "', modify
label define DNAME 20 `"Dolakha       "', modify
label define DNAME 21 `"Dolpa         "', modify
label define DNAME 22 `"Doti          "', modify
label define DNAME 23 `"Gorkha        "', modify
label define DNAME 24 `"Gulmi         "', modify
label define DNAME 25 `"Humla         "', modify
label define DNAME 26 `"Ilam          "', modify
label define DNAME 27 `"Jajarkot      "', modify
label define DNAME 28 `"Jhapa         "', modify
label define DNAME 29 `"Jumla         "', modify
label define DNAME 30 `"Kailali       "', modify
label define DNAME 31 `"Kalikot       "', modify
label define DNAME 32 `"Kanchanpur    "', modify
label define DNAME 33 `"Kapilbastu    "', modify
label define DNAME 34 `"Kaski         "', modify
label define DNAME 35 `"Kathmandu     "', modify
label define DNAME 36 `"Kavrepalanchok"', modify
label define DNAME 37 `"Khotang       "', modify
label define DNAME 38 `"Lalitpur      "', modify
label define DNAME 39 `"Lamjung       "', modify
label define DNAME 40 `"Mahottari     "', modify
label define DNAME 41 `"Makwanpur     "', modify
label define DNAME 42 `"Manang        "', modify
label define DNAME 43 `"Morang        "', modify
label define DNAME 44 `"Mugu          "', modify
label define DNAME 45 `"Mustang       "', modify
label define DNAME 46 `"Myagdi        "', modify
label define DNAME 47 `"Nawalparasi   "', modify
label define DNAME 48 `"Nuwakot       "', modify
label define DNAME 49 `"Okhaldhunga   "', modify
label define DNAME 50 `"Palpa         "', modify
label define DNAME 51 `"Panchthar     "', modify
label define DNAME 52 `"Parbat        "', modify
label define DNAME 53 `"Parsa         "', modify
label define DNAME 54 `"Pyuthan       "', modify
label define DNAME 55 `"Ramechhap     "', modify
label define DNAME 56 `"Rasuwa        "', modify
label define DNAME 57 `"Rautahat      "', modify
label define DNAME 58 `"Rolpa         "', modify
label define DNAME 59 `"Rukum         "', modify
label define DNAME 60 `"Rupandehi     "', modify
label define DNAME 61 `"Salyan        "', modify
label define DNAME 62 `"Sankhuwasabha "', modify
label define DNAME 63 `"Saptari       "', modify
label define DNAME 64 `"Sarlahi       "', modify
label define DNAME 65 `"Sindhuli      "', modify
label define DNAME 66 `"Sindhupalchok "', modify
label define DNAME 67 `"Siraha        "', modify
label define DNAME 68 `"Solukhumbu    "', modify
label define DNAME 69 `"Sunsari       "', modify
label define DNAME 70 `"Surkhet       "', modify
label define DNAME 71 `"Syangja       "', modify
label define DNAME 72 `"Tanahu        "', modify
label define DNAME 73 `"Taplejung     "', modify
label define DNAME 74 `"Terhathum     "', modify
label define DNAME 75 `"Udayapur      "', modify
