label define DIST 1 `"Taplejung"', modify
label define DIST 2 `"Panchthar"', modify
label define DIST 3 `"Ilam"', modify
label define DIST 4 `"Jhapa"', modify
label define DIST 5 `"Morang"', modify
label define DIST 6 `"Sunsari"', modify
label define DIST 7 `"Dhankuta"', modify
label define DIST 8 `"Terhathum"', modify
label define DIST 9 `"Sankhuwasabha"', modify
label define DIST 10 `"Bhojpur"', modify
label define DIST 11 `"Solukhumbu"', modify
label define DIST 12 `"Okhaldhunga"', modify
label define DIST 13 `"Khotang"', modify
label define DIST 14 `"Udayapur"', modify
label define DIST 15 `"Saptari"', modify
label define DIST 16 `"Siraha"', modify
label define DIST 17 `"Dhanusa"', modify
label define DIST 18 `"Mahottari"', modify
label define DIST 19 `"Sarlahi"', modify
label define DIST 20 `"Sindhuli"', modify
label define DIST 21 `"Ramechhap"', modify
label define DIST 22 `"Dolakha"', modify
label define DIST 23 `"Sindhupalchok"', modify
label define DIST 24 `"Kavrepalanchok"', modify
label define DIST 25 `"Lalitpur"', modify
label define DIST 26 `"Bhaktapur"', modify
label define DIST 27 `"Kathmandu"', modify
label define DIST 28 `"Nuwakot"', modify
label define DIST 29 `"Rasuwa"', modify
label define DIST 30 `"Dhading"', modify
label define DIST 31 `"Makwanpur"', modify
label define DIST 32 `"Rautahat"', modify
label define DIST 33 `"Bara"', modify
label define DIST 34 `"Parsa"', modify
label define DIST 35 `"Chitawan"', modify
label define DIST 36 `"Gorkha"', modify
label define DIST 37 `"Lamjung"', modify
label define DIST 38 `"Tanahu"', modify
label define DIST 39 `"Syangja"', modify
label define DIST 40 `"Kaski"', modify
label define DIST 41 `"Manang"', modify
label define DIST 42 `"Mustang"', modify
label define DIST 43 `"Myagdi"', modify
label define DIST 44 `"Parbat"', modify
label define DIST 45 `"Baglung"', modify
label define DIST 46 `"Gulmi"', modify
label define DIST 47 `"Palpa"', modify
label define DIST 48 `"Nawalparasi"', modify
label define DIST 49 `"Rupandehi"', modify
label define DIST 50 `"Kapilbastu"', modify
label define DIST 51 `"Arghakhanchi"', modify
label define DIST 52 `"Pyuthan"', modify
label define DIST 53 `"Rolpa"', modify
label define DIST 54 `"Rukum"', modify
label define DIST 55 `"Salyan"', modify
label define DIST 56 `"Dang"', modify
label define DIST 57 `"Banke"', modify
label define DIST 58 `"Bardiya"', modify
label define DIST 59 `"Surkhet"', modify
label define DIST 60 `"Dailekh"', modify
label define DIST 61 `"Jajarkot"', modify
label define DIST 62 `"Dolpa"', modify
label define DIST 63 `"Jumla"', modify
label define DIST 64 `"Kalikot"', modify
label define DIST 65 `"Mugu"', modify
label define DIST 66 `"Humla"', modify
label define DIST 67 `"Bajura"', modify
label define DIST 68 `"Bajhang"', modify
label define DIST 69 `"Achham"', modify
label define DIST 70 `"Doti"', modify
label define DIST 71 `"Kailali"', modify
label define DIST 72 `"Kanchanpur"', modify
label define DIST 73 `"Dadeldhura"', modify
label define DIST 74 `"Baitadi"', modify
label define DIST 75 `"Darchula"', modify
