label define district 1 `"Taplejung"', modify
label define district 2 `"Panchthar"', modify
label define district 3 `"Ilam"', modify
label define district 4 `"Jhapa"', modify
label define district 5 `"Morang"', modify
label define district 6 `"Sunsari"', modify
label define district 7 `"Dhankuta"', modify
label define district 8 `"Terhathum"', modify
label define district 9 `"Sankhuwasabha"', modify
label define district 10 `"Bhojpur"', modify
label define district 11 `"Solukhumbu"', modify
label define district 12 `"Okhaldhunga"', modify
label define district 13 `"Khotang"', modify
label define district 14 `"Udayapur"', modify
label define district 15 `"Saptari"', modify
label define district 16 `"Siraha"', modify
label define district 17 `"Dhanusa"', modify
label define district 18 `"Mahottari"', modify
label define district 19 `"Sarlahi"', modify
label define district 20 `"Sindhuli"', modify
label define district 21 `"Ramechhap"', modify
label define district 22 `"Dolakha"', modify
label define district 23 `"Sindhupalchok"', modify
label define district 24 `"Kavre"', modify
label define district 25 `"Lalitpur"', modify
label define district 26 `"Bhaktapur"', modify
label define district 27 `"Kathmandu"', modify
label define district 28 `"Nuwakot"', modify
label define district 29 `"Rasuwa"', modify
label define district 30 `"Dhading"', modify
label define district 31 `"Makwanpur"', modify
label define district 32 `"Rautahat"', modify
label define district 33 `"Bara"', modify
label define district 34 `"Parsa"', modify
label define district 35 `"Chitawan"', modify
label define district 36 `"Gorkha"', modify
label define district 37 `"Lamjung"', modify
label define district 38 `"Tanahu"', modify
label define district 39 `"Syangja"', modify
label define district 40 `"Kaski"', modify
label define district 41 `"Manang"', modify
label define district 42 `"Mustang"', modify
label define district 43 `"Myagdi"', modify
label define district 44 `"Parbat"', modify
label define district 45 `"Baglung"', modify
label define district 46 `"Gulmi"', modify
label define district 47 `"Palpa"', modify
label define district 48 `"Nawalparasi"', modify
label define district 49 `"Rupandehi"', modify
label define district 50 `"Kapilbastu"', modify
label define district 51 `"Arghakhanchi"', modify
label define district 52 `"Pyuthan"', modify
label define district 53 `"Rolpa"', modify
label define district 54 `"Rukum"', modify
label define district 55 `"Salyan"', modify
label define district 56 `"Dang"', modify
label define district 57 `"Banke"', modify
label define district 58 `"Bardiya"', modify
label define district 59 `"Surkhet"', modify
label define district 60 `"Dailekh"', modify
label define district 61 `"Jajarkot"', modify
label define district 62 `"Dolpa"', modify
label define district 63 `"Jumla"', modify
label define district 64 `"Kalikot"', modify
label define district 65 `"Mugu"', modify
label define district 66 `"Humla"', modify
label define district 67 `"Bajura"', modify
label define district 68 `"Bajhang"', modify
label define district 69 `"Achham"', modify
label define district 70 `"Doti"', modify
label define district 71 `"Kailali"', modify
label define district 72 `"Kanchanpur"', modify
label define district 73 `"Dadeldhura"', modify
label define district 74 `"Baitadi"', modify
label define district 75 `"Darchula"', modify
